on:
  issues:
    types:
      - opened
  push:
    branches:
      - main
    
name: dev deployment
jobs:
  setup: 
    name: Setup
    runs-on: ubuntu-latest

    outputs:
      branch: ${{ steps.dev.outputs.git-branch }}
    
    steps:
      - name: Environment Setup - Staging
        if: startsWith(github.event.issue.title, 'deploy')

        id: staging
        run: |
          echo "::set-output name=git-branch::$(echo ${{ github.event.issue.title }} | sed 's/^deploy //I')"
  
  build:
    if: needs.setup.outputs.branch
    needs: [setup]
    environment: dev
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup.outputs.git-branch }}
  
  close-issue:
    name: Close GitHub issue
    runs-on: ubuntu-18.04

    if: startsWith(github.event.issue.title, 'deploy')
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Deployed branch
            Auto-closing this issue.