on:
  issues:
    types:
      - opened
  push:
    branches:
      - master

name: dev deployment
jobs:
  setup: 
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      git-branch: ${{ steps.dev.outputs.git-branch  ||  steps.devmain.outputs.git-branch }}
    steps:
      - name: dev-deployment-any-branch
        if: startsWith(github.event.issue.title, 'deploy')
        id: dev
        run: |
          echo "::set-output name=git-branch::$(echo ${{ github.event.issue.title }} | sed 's/^deploy //I')"
    
      - name: main branch deployment
        if: github.event_name == 'push'
        id: devmain
        run: |
          echo "::set-output name=git-branch::main"

  build:
    if: needs.setup.outputs.git-branch
    needs: [ setup ]
    environment: dev
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ needs.setup.outputs.git-branch }}
      - name: Deploy
        run: |
          curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/kubectl
          echo $(kubectl version)
          echo $(./kubectl version)

  close-issue:
    name: Close GitHub issue
    runs-on: ubuntu-18.04
    needs: [ build ]
    if: startsWith(github.event.issue.title, 'deploy')
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            Deployed branch
            Auto-closing this issue.
